/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cefet.pc2.trabalhospraticos.figurasgeometricas.src.view.gui.melhorada;

import com.cefet.pc2.trabalhospraticos.figurasgeometricas.src.control.gu_melhorada.IController;
import com.cefet.pc2.trabalhospraticos.figurasgeometricas.src.control.gu_melhorada.MainController;
import com.cefet.pc2.trabalhospraticos.figurasgeometricas.src.model.FigurasGeometricas;
import com.cefet.pc2.trabalhospraticos.figurasgeometricas.src.model.Renderizavel;
import com.cefet.pc2.trabalhospraticos.figurasgeometricas.src.model.Texto;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Everton
 */
public class PaneListarTodos extends javax.swing.JPanel {

    private IController controller = new MainController();

    /**
     * Creates new form PaneListarTodos
     */
    public PaneListarTodos() {
        initComponents();
        atualizaTabela();

    }

    public void atualizaTabela() {
        List<Renderizavel> lsta = this.controller.findAll();
        DefaultTableModel model = (DefaultTableModel) this.tabelaTodos.getModel();
        model.setRowCount(0);
        for (Renderizavel item : lsta) {
            if (item instanceof FigurasGeometricas) {
                model.addRow(new Object[]{
                    item.getClass().getSimpleName(),
                    item.getId(),
                    "",
                    ((FigurasGeometricas) item).calcularArea(),
                    ((FigurasGeometricas) item).calcularPerimetro(),
                    ""
                });
            }
            if (item instanceof Texto) {
                model.addRow(new Object[]{
                    item.getClass().getSimpleName(),
                    item.getId(),
                    "",
                    "",
                    "",
                    ((Texto) item).getText()
                });

            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTodos = new javax.swing.JTable();

        tabelaTodos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Objeto", "ID", "Info", "Area", "Perimetro", "Texto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaTodos);
        if (tabelaTodos.getColumnModel().getColumnCount() > 0) {
            tabelaTodos.getColumnModel().getColumn(0).setResizable(false);
            tabelaTodos.getColumnModel().getColumn(1).setResizable(false);
            tabelaTodos.getColumnModel().getColumn(1).setPreferredWidth(2);
            tabelaTodos.getColumnModel().getColumn(3).setResizable(false);
            tabelaTodos.getColumnModel().getColumn(3).setPreferredWidth(10);
            tabelaTodos.getColumnModel().getColumn(4).setResizable(false);
            tabelaTodos.getColumnModel().getColumn(4).setPreferredWidth(10);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaTodos;
    // End of variables declaration//GEN-END:variables
}
